### ISSUE TITLE
the £DESKTOP  command

### ISSUE THREAD

**Issue by limingke** [EgeBalci/ARCANUS#3]
can you tell me how to use "£DESKTOP "?

**Comment by EgeBalci** [comment]
Sure

but in order to execute £DESKTOP command you need to have administrator
privileges on remote machine, by the way £DESKTOP command don't launches
remote desktop connection it just adjusts the remote desktop configurations
for manual connections that means after you execute £DESKTOP command on
remote machine you need to connect manualy.

In new version of ARCANUS i will improve £DESKTOP command for full
automatic remote desktop connections.

2016-04-07 16:29 GMT+03:00 limingke notifications@github.com:
