### ISSUE TITLE
Using over the internet

### ISSUE THREAD

**Issue by BestAndroid** [EgeBalci/ARCANUS#6]
If I want to use it over the internet I've heard that I have to open ports of my router (eg.4444) but I do not have any router, I just have a broadband connection......then how can open any port ??? and where will I open any port ? and how will I open any port ?  pls help!!!

**Comment by EgeBalci** [comment]
Yes in order to use it on internet you need to forward your routers ports to your computer, if you don't have access to router you can't use it over the internet, there is two simple solution to this first one is you can rent a web host and run ARCANUS on that host via ssh, if you do that you don't need to forward any ports.Second you can use your mobile phones hotspot, this app allows you to forward ports https://play.google.com/store/apps/details?id=at.bherbst.net
